apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
  namespace: dev
data:
  appsettings.secrets.json: ew0KICAiTG9nZ2luZyI6IHsNCiAgICAiTG9nTGV2ZWwiOiB7DQogICAgICAiRGVmYXVsdCI6ICJJbmZvcm1hdGlvbiIsDQogICAgICAiTWljcm9zb2Z0LkFzcE5ldENvcmUiOiAiV2FybmluZyINCiAgICB9DQogIH0sDQogICJBbGxvd2VkSG9zdHMiOiAiKiIsDQogICAiRGF0YWJhc2VTZXR0aW5ncyI6IHsNCiAgICAiREJQcm92aWRlciI6ICJteXNxbCIsDQogICAgIkNvbm5lY3Rpb25TdHJpbmciOiAiU2VydmVyPW15c3FsO1BvcnQ9MzMwNjtEYXRhYmFzZT1yb290O1VpZD1yb290O3Bhc3N3b3JkPXJvb3Q7IiwNCiAgICAiRGF0YWJhc2VOYW1lIjogInJvb3QiDQogIH0NCn0NCg==
type: Opaque